version: "3"
services:

  webserver:
    image: nginx
    volumes:
      - ./etc/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    ports:
    - "80:80"

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    environment:
      RAZZLE_INTERNAL_API_PATH: http://webserver:80
      # RAZZLE_DEV_PROXY_API_PATH: http://varnish:80
    ports:
    - "3000:3000"

  varnish:
    image: varnish:7.1.0
    volumes:
      - ./etc/varnish.vcl:/etc/varnish/default.vcl
    ports:
      - "8000:80"
    depends_on:
      - backend

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      SITE: Plone
      PROFILES: "plone.app.caching:with-caching-proxy"
    ports:
    - "8080:8080"
