[tool.black]
line-length = 88
target-version = ['py37']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.pytest_cache
  | docs
  | requirements
)/
'''

[tool.isort]
sections = 'FUTURE,STDLIB,HTTP,CLI,PYTEST,THIRDPARTY,FIRSTPARTY,LOCALFOLDER'
force_single_line = true
known_future_library = 'future,pies'
known_pytest = 'pytest,py.test,pytest_asyncio,pytest_docker_fixtures,freezegun'
known_http = 'httpx'
known_cli = 'typer'
known_first_party = ''
import_heading_stdlib = 'Standard Library'
import_heading_http = 'HTTP Library'
import_heading_cli = 'CLI Library'
import_heading_pytest = 'pytest'
import_heading_firstparty = 'Volto'
lines_after_imports = 2
include_trailing_comma = true
force_grid_wrap = false
combine_as_imports = true
line_length = 88

[tool.pytest.ini_options]
asyncio_mode = "strict"
testpaths = [
    "tests",
]
